# Generated by Django 4.2.8 on 2024-05-20 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchangerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkpr', models.FloatField()),
                ('cur_nm', models.CharField(max_length=16)),
                ('cur_unit', models.CharField(max_length=16)),
                ('deal_bas_r', models.FloatField()),
                ('kftc_bkpr', models.FloatField()),
                ('kftc_deal_bas_r', models.FloatField()),
                ('ten_dd_efee_r', models.IntegerField()),
                ('ttb', models.FloatField()),
                ('tts', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('dcls_month', models.TextField()),
                ('fin_co_no', models.TextField()),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_cd', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.TextField()),
                ('join_member', models.TextField()),
                ('etc_note', models.TextField()),
                ('intr_rate_type', models.TextField(null=True)),
                ('intr_rate_type_nm', models.TextField(null=True)),
                ('rsrv_type', models.TextField(null=True)),
                ('rsrv_type_nm', models.TextField(null=True)),
                ('save_trm', models.TextField()),
                ('intr_rate', models.IntegerField(null=True)),
                ('intr_rate2', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
